
/* Q3_A: Using 2 tasks, one for the motors, one for analysing distances using Ultrassonic sensor, and one function for turning the robot.
The general idea is to move both motors a distance of 20cm (using the encoder in the motors) at the speed of 25, then the robot using the function turn the angle of 90 degrees clockwise and analyses the square in the center of the track
if the robot senses something in front of him, he will turn 90 degrees counter-clockwise and continue the lap */

#pragma config(StandardModel, "EV3_REMBOT")
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

int degree = 0;
int gyro = 0;
int enc;
int enc1;
int Distance = 0;
int speedB = 20;
int speedC = 20;
int speedCReverse = -20;
const unsigned int motorhertz = 1000/20;
const unsigned int mainhertz = 1000/50;
const unsigned int USsensorhertz = 1000/50;

task analyse()
{
	while(true)
	{
	Distance = getUSDistance(S4);
	sleep (USsensorhertz);
	}
}

void TurnUSD()
{
		resetGyro(S2);

		setMotorSpeed(motorB, 0);
		setMotorSpeed(motorC, 0);

		sleep(1000);

		setMotorSpeed(motorB, speedB);
		setMotorSpeed(motorC, speedCReverse);

			if(degree >= 90)
			{
				speedB = 0;
				speedCReverse = 0;
			}
			else
			{
				speedB = 20;
				speedCReverse = -20;
		}

}


task moveUntil(){
	while(true)
	{
		setMotorSpeed(motorB,speedB);
		setMotorSpeed(motorC,speedC);
		sleep(motorhertz);
	}
}



task main()
{
	while(true)
	{


		enc=getMotorEncoder(motorB);
		enc1=getMotorEncoder(motorC);

		displayTextLine(1,"Encoder B Val = %d", enc);
		displayTextLine(2,"Encoder C Val = %d", enc1);

		startTask(moveUntil);
		startTask(analyse);

		if(enc >= 480)											//about 20cm the robot will move then turn and analyse
		{
			stopTask(moveUntil);
			TurnUSD();

			enc=getMotorEncoder(motorB);
			enc1=getMotorEncoder(motorC);

			displayTextLine(1,"Encoder B Val = %d", enc);
			displayTextLine(2,"Encoder C Val = %d", enc1);

			sleep(3000);

		}



}
}
