#pragma config(StandardModel, "EV3_REMBOT")
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

int globalDistanceValue = 0;
int globalGyroValue = 0;
int motorSpeedA = 25;
int motorSpeedB = 25;
bool turnFlag1 = false;
bool turnFlag2 = false;

task distanceSensor_1(){
	while(true){
		globalDistanceValue = getUSDistance(S4);
		sleep(1);
	}
}

task gyroSensor_1(){
	while(true){
		globalGyroValue = getGyroDegrees(S2);
	}
}

task motorControl_1(){
	while(true)
	{
		if((globalDistanceValue) < 14 && (turnFlag2 == true)){
		  while(globalGyroValue < 75)
		  	{
		  		setMotorSpeed(motorB, 50);
		  		setMotorSpeed(motorC, -50);
		  	}
		  //turnFlag2 = true;
		}
		if((globalDistanceValue) < 14 && (turnFlag1 == true)){
		  while(globalGyroValue < 75)
		  	{
		  		setMotorSpeed(motorB, 50);
		  		setMotorSpeed(motorC, -50);
		  	}
		  turnFlag2 = true;
		  resetGyro(S2);
		}
		setMotorSpeed(motorB, motorSpeedA);
		setMotorSpeed(motorC, motorSpeedB);
		sleep(100);
		if ((globalDistanceValue < 13) && (turnflag1 == false))
			{
				setMotorSpeed(motorB, 0);
				setMotorSpeed(motorC, 0);
				//globalDistanceValue = 0;
				while(globalGyroValue > -75)
					{
						setMotorSpeed(motorB, -50);
						setMotorSpeed(motorC, 50);
						//turnFlag1 = true;
					}
					resetGyro(S2);
					turnFlag1 = true;
			}
	}
}


task main()
{
	startTask(distanceSensor_1);
	startTask(gyroSensor_1);
	startTask(motorControl_1);
	while(true){
		displayTextLine(0,"%d",globalDistanceValue);
		sleep(20);
	}
}
