#pragma config(StandardModel, "EV3_REMBOT")
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
	resetGyro(S2);

	repeatUntil(getGyroDegrees(S2) > 90){
		setMotorSpeed(motorC, -50);
		setMotorSpeed(motorB, 50);
	}

	setMotorSpeed(motorB, 0);
	setMotorSpeed(motorC, 0);

	resetGyro(S2);

	repeatUntil(getGyroDegrees(S2) < -180){
		setMotorSpeed(motorC, 50);
		setMotorSpeed(motorB, -50);
	}

	setMotorSpeed(motorB, 0);
	setMotorSpeed(motorC, 0);

	resetGyro(S2);

	repeatUntil(getGyroDegrees(S2) > 270){
		setMotorSpeed(motorC, -50);
		setMotorSpeed(motorB, 50);
	}

	setMotorSpeed(motorB, 0);
	setMotorSpeed(motorC, 0);

}
