#pragma config(StandardModel, "EV3_REMBOT")
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//
int globalGyroSensorValue = 0;
int globalTurnDegreeValue = 0;

// motor power levels
const unsigned int motorTurnPower=50;
const unsigned int motorIdlePower=0;
int motorPower;

// states
enum STATES{IDLE=0,	TURNING=1};
enum STATES state; // variable to hold current State
string stateNames[]={"IDLE","TURNING"};

// turn degree threshold
int rotationThreshold=360;

task turnSensor()
{
		while(true)
		{
			globalGyroSensorValue = getGyroDegrees(S2);
		}
}


task turnSyncMotor()
{
		while(true)
		{
			setMotorSync(motorB, motorC,100,motorPower);
			//globalTurnDegreeValue = getMotorEncoder(motorB);
		}
}

task DisplayTask(){
	while(1)
	{
		displayTextLine(1,"State = %s",stateNames[state]);
		displayTextLine(3,"Distance = %d",globalGyroSensorValue);
		displayTextLine(5,"Motor Power = %d",motorPower);
		sleep(200);
	}
}

task main()
{

  //initialize states and variables
	state=IDLE;
	motorPower=motorIdlePower;

	startTask(turnSensor);
	startTask(turnSyncMotor);
	startTask(DisplayTask);

	while(1)
	{
		// state transition table
		switch (state)
		{
		case IDLE:
			if(globalGyroSensorValue<=rotationThreshold)
			{
				state=TURNING;
			}
			break;
		case TURNING:
			if(globalGyroSensorValue>rotationThreshold)
			{
				state=IDLE;
			}
			break;
		default:
			state=IDLE;
			break;
		}
		// state execution table
		switch (state)
		{
		case IDLE:
			motorPower=motorIdlePower;
			break;
		case TURNING:
			motorPower=motorTurnPower;
			break;
		default:
			motorPower=motorIdlePower;
			break;
		}
		sleep(20);
	}
}
