#pragma config(StandardModel, "EV3_REMBOT")
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

// motor power levels
const unsigned int motorTurnPower=25;
const unsigned int motorIdlePower=0;
const unsigned int sensorhertz = 1000/25;
int globalColorValue = 0;
int motorPower;
//int globalDistance;
//int target_distance=30;

enum STATES{IDLE=0,	FORWARD=1};
enum STATES state; // variable to hold current State
string stateNames[]={"IDLE","FORWARD"};

int forwardSyncMotorDelay = 1000/60;
int main_delay = 1000/60;

task forwardSyncMotor()
{
	while(true)
	{
		setMotorSync(motorB, motorC,0,motorPower);
		sleep(forwardSyncMotorDelay);
	}
}

//task getDist(){
//	while(1){
//		globalDistance=getUSDistance(sonarSensor);
//		sleep(20);
//}
//}
task senseColors(){
	while(true){
	globalColorValue = getColorName(S3);
	sleep(sensorhertz);
	}
}

task main()
{
	state=IDLE;
	motorPower=motorIdlePower;

	startTask(forwardSyncMotor);
	//startTask(getDist);
	startTask(senseColors);
	while(1)
	{
		// state transition table
		switch (state)
		{
		case IDLE:
			if(globalColorValue!=5)
			{
				state=FORWARD;
			}
			break;
		case FORWARD:
			if(globalColorValue==5)
			{
				state=IDLE;
			}
			break;
		default:
			state=IDLE;
			break;
		}
		// state execution table
		switch (state)
		{
		case IDLE:
			motorPower=motorIdlePower;
			break;
		case FORWARD:
			motorPower=motorTurnPower;
			break;
		default:
			motorPower=motorIdlePower;
			break;
		}
		sleep(20);
	}





}
