#pragma config(StandardModel, "EV3_REMBOT")
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//


int globalTouchValue = 0;

task touchSensor1(){
	while(true){
	globalTouchValue = getTouchValue(S1);
	sleep(100);
	}
}

task moveMotors(){
	repeatUntil(globalTouchValue == 1)
	{
		setMotorSpeed(motorB, 50);
		setMotorSpeed(motorC, 50);
		sleep(100);
	}
	setMotorSpeed(motorB, 0);
	setMotorSpeed(motorC, 0);
}

task main()
{
	startTask(touchSensor1);
	startTask(moveMotors);
	while(true){
		displayTextLine(0,"%d", globalTouchValue);
		sleep(20);
	}
}



	 //Repeat the loop until the Touch Sensor is pressed (returns a value of 1)
// repeatUntil(getTouchValue(S1) == 1)
// {
   //Set both left and right motors to run at 50% speed (continuously)

// 	 setMotorSpeed(motorB, 50);
//   setMotorSpeed(motorC, 50);
//   displayTextLine(3, "%s", "still 0");
// 	 displayTextLine(0, "%d", globalTouchValue);
// }
// globalTouchValue = 1;
// displayTextLine(0, "%d", globalTouchValue);

 //Stop the motors after the movement is complete
// setMotorSpeed(motorB, 0);
// setMotorSpeed(motorC, 0);
