#pragma config(StandardModel, "EV3_REMBOT")
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//
int globalGyroValue = 0;

task gyroSensor1(){
	while(true){
	globalGyroValue = getGyroDegrees(S2);
	sleep(200);
	}
}

task motorControl(){
	repeatUntil(globalGyroValue > 90){
			setMotorSpeed(motorC, -50);
			setMotorSpeed(motorB, 50);
		}

		setMotorSpeed(motorB, 0);
		setMotorSpeed(motorC, 0);

}


task main(){
	startTask(gyroSensor1);
	startTask(motorControl);
	while(true){
		displayTextLine(0,"%d", globalGyroValue);
		sleep(20);
	}
//	displayTextLine(0,"%d", globalTouchValue);
}
