#pragma config(StandardModel, "EV3_REMBOT")
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//
int globalGyroValue = 0;
int Degrees = 30;
int SpeedC = -15;
int SpeedB = 15;
bool flag30 = false;
bool flag45 = false;
bool flag90 = false;

task gyroSensor1(){
	while(true){
	globalGyroValue = getGyroDegrees(S2);
	sleep(20);
	}
}

task motorControl(){
	while(1){
			setMotorSpeed(motorC, SpeedC);
			setMotorSpeed(motorB, SpeedB);
		}
	}

task DebugStream(){
		while(true){
		writeDebugStreamLine("%d", globalGyroValue);
		sleep(200);
	}
}


task main(){
	startTask(gyroSensor1);
	startTask(motorControl);
	clearDebugStream();
	startTask(DebugStream);
	while(true){

		if (globalGyroValue >= 30 && globalGyroValue < 44 && !flag30){
			SpeedC=0;
			SpeedB=0;
			sleep(1000);
			Degrees=45;
			SpeedC=-15;
			SpeedB=15;
			flag30=true;
	}
		if (globalGyroValue >= 45 && globalGyroValue < 89&& !flag45){
			SpeedC=0;
			SpeedB=0;
			sleep(1000);
			Degrees=90;
			SpeedC=-15;
			SpeedB=15;
			flag45=true;
	}
			if (globalGyroValue >= 90 && globalGyroValue < 134&& !flag90){
			SpeedC=0;
			SpeedB=0;
			sleep(1000);
			Degrees=135;
			SpeedC=-15;
			SpeedB=15;
			flag90=true;
	}
			if (globalGyroValue >= 135){
			SpeedC=0;
			SpeedB=0;

	}


	}
}
