#pragma config(StandardModel, "EV3_REMBOT")
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

int init_startD = 89; //White
int init_startC = 0 ; //Black

double colorMin = (init_startC + init_startD) / 2; // Average

