#pragma config(StandardModel, "EV3_REMBOT")
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

enum STATES{IDLE=0 ,	LEFT=1 , RIGHT=2};
enum STATES state = IDLE;

int starting_point_D = 89; //White
int starting_point_C = 0 ; //Black
float threshold = (starting_point_C + starting_point_D) / 2; // The value at which we should change states.

double current_color = -1;
int monitor_sensor_color_delay = 1000 / 120;

int motor_power = 0;
double motor_turn_ratio = 0;
double turn_ratio_master;
int controller_motor_delay = 1000 / 120;

int debug_delay = 1000 / 5;

task monitor_sensor_color(){
	while(true){
		current_color = getColorReflected(S3);
		sleep(monitor_sensor_color_delay);
	}
}

task controller_motor(){
	int prev_power = 0;
	int prev_ratio = 0;
	while(true){
		if(prev_power != motor_power || prev_ratio != motor_turn_ratio){
			setMotorSync(motorB , motorC , motor_turn_ratio , motor_power);
		}
		prev_power = motor_power;
		prev_ratio = motor_turn_ratio;
		sleep(controller_motor_delay);
	}
}

task debug(){
	while(true){
		writeDebugStreamLine("current_color=%d\n\t motor_power=%d\n\t\t motor_turn_ratio=%d\n\t\t\t state=%d" , current_color , motor_power , motor_turn_ratio , state);
		sleep(debug_delay);
	}
}

//We will be on the left side of the line

task main()
{
	clearDebugStream();
	startTask(monitor_sensor_color);
	startTask(controller_motor);
	startTask(debug);

	motor_power = 16;
	turn_ratio_master = 50;
	sleep(256);

	while(true){
		switch(state){
			case IDLE:
				if(current_color > threshold) state = LEFT;
				if(current_color <= threshold) state = RIGHT;
				break;
			case LEFT:
				if(current_color <= threshold) state = RIGHT;
				break;
			case RIGHT:
				if(current_color > threshold) state = LEFT;
				break;
		}
		switch(state){
			case IDLE:
				break;
			case LEFT:
				motor_turn_ratio = turn_ratio_master;
				break;
			case RIGHT:
				motor_turn_ratio = -1 * turn_ratio_master;
				break;
		}
	}
}
