#pragma config(StandardModel, "EV3_REMBOT")
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

int starting_point_D = 89; //White
int starting_point_C = 0 ; //Black

double threshold = (starting_point_C + starting_point_D) / 2; // The value at which we should change states.

task main()
{



}
