#pragma config(StandardModel, "EV3_REMBOT")
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

enum STATES{IDLE=0, LEFT=1, RIGHT=2};
enum STATES state = IDLE;
//Light
int init_startD = 90;
//Dark
int init_startC = 0 ;
//minimum threshold
float colorMin = (init_startC + init_startD) / 2;

double this_color = -1;
int colorSenseDelay = 1000 / 1000;
const int start_motor_power = 20;
int _power = start_motor_power;
const double init_motor_turn_ratio = 75;
double turnRatio = beginningTurn_ratio;
int controller_motor_delay = 1000 / 1000;
int turn_gain = 1.5;
int debug_sleep = 1000 / 5;


task senseColor()
{
	while(true)
    {
		this_color = getColorReflected(S3);
		sleep(colorSenseDelay);
	}
}

task motorControl()
{
	int prev_power = 0;
	int prev_ratio = 0;
	while(true)
    {
		if(prev_power != _power || prev_ratio != turnRatio){
			setMotorSync(motorB , motorC , turnRatio , _power);
		}
		prev_power = _power;
		prev_ratio = turnRatio;
		sleep(controller_motor_delay);
	}
}

task debug(){
	while(true){
		writeDebugStreamLine("current_color=%d\n\t motor_power=%d\n\t\t motor_turn_ratio=%d\n\t\t state=%d" , this_color, _power, turnRatio, state);
		sleep(debug_sleep);
	}
}

double proportionRatio(){
	double discrepancy = this_color - colorMin;
	double out = (turn_gain * discrepancy) / (colorMin * turn_gain);
	out *= beginningTurn_ratio;
	return out;
}

task main()
{
	clearDebugStream();
	startTask(senseColor);
	startTask(motorControl);
	startTask(debug);

	sleep(256);

	while(true)
    {
		switch(state)
        {
			case IDLE:
				if(this_color > colorMin) state = LEFT;
				if(this_color <= colorMin) state = RIGHT;
				break;
			case LEFT:
				if(this_color <= colorMin) state = RIGHT;
				break;
			case RIGHT:
				if(this_color > colorMin) state = LEFT;
				break;
		}

		switch(state)
        {
			case IDLE:
				break;
			case LEFT:
				turnRatio = proportionRatio();
				break;
			case RIGHT:
				turnRatio = proportionRatio();
				break;
		}
	}
}
