#pragma config(StandardModel, "EV3_REMBOT")
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
	displayTextLine(1, "Hello World!");
	sleep(10000);
}
