#pragma config(StandardModel, "EV3_REMBOT")
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

void HelloWorld()
{
	displayCenteredBigTextLine(1, "Hello World!");
	sleep(1000);
}

void ClearLine()
{
	displayCenteredBigTextLine(1, "  ");
	sleep(1000);
}

task main()
{
	for(int i = 0; i < 5; i++)
	{
		HelloWorld();
		ClearLine();
	}
}
