#pragma config(StandardModel, "EV3_REMBOT")
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

void HelloWorld(int time)
{
	displayCenteredBigTextLine(1, "Hello World!");
	sleep(time);
}

void ClearLine(int time)
{
	displayCenteredBigTextLine(1, "  ");
	sleep(time);
}

task main()
{
	for(int i = 0; i < 5; i++)
	{
		HelloWorld(500);
		ClearLine(500);
	}
}
