#pragma config(StandardModel, "EV3_REMBOT")
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//
void squares()
{
	for(int i=1; i<9; i++)
	{
  	displayTextLine(i, "%d squared is %d", i, (i*i));
  	sleep(1000)
  	displayTextLine(i, "  ");
	}
}

task main()
{
	squares();
}
