#pragma config(StandardModel, "EV3_REMBOT")
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

//Recursion in a small system has the pros of readibility as well as reduced
//time complexity, however recursion also has the possibility of being slower
//as well as taking up more memory

int values[20];

int fibRec(int termNum)
{
	int term;
	if (termNum <= 2)
		term = 1;
	else
		term = fibRec(termNum - 1) + fibRec(termNum - 2);
	return term;
}

void fibHelper()
{
	for(int i=0; i<21; i++)
	{
		values[i]=fibRec(i)
	}
}

task main()
{
	bool x=true;
	int i=0;
	fibHelper();
	while(x)
	{
		if(i<21)
		{
			displayCenteredBigTextLine(1, "%d", values[i]);
			sleep(1000)
			displayCenteredBigTextLine(1, "   ");
			i++;
		}
		else
		{
			i=0;
		}
	}
}
