#pragma config(StandardModel, "EV3_REMBOT")
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

const float degreesPerRotation = 360.0;
const float time_for_360 = 8175;
const float time_per_degree = time_for_360 / degreesPerRotation;

void pointTurn(int degree)
{
	int degreePerMillisecond = time_per_degree * degree;
	setMotorSpeed(motorB, -20);
	setMotorSpeed(motorC, 20);
	sleep(degreePerMillisecond);
	setMotorSpeed(motorB, 0);
	setMotorSpeed(motorB, 0);

}

task main()
{
	pointTurn(degreesPerRotation);
}
