#pragma config(StandardModel, "EV3_REMBOT")
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

const int time_for_1_meter = 8550;

void moveStraight(int sleep_time)
{
	setMotorSpeed(motorB, 50);
	setMotorSpeed(motorC, 50);
	sleep(sleep_time);
	setMotorSpeed(motorB, 50);
	setMotorSpeed(motorC, 50);
	}

task main()
{
	moveStraight(time_for_1_meter);
}
