#pragma config(StandardModel, "EV3_REMBOT")
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

const int time_for_1_meter = 8550;
const float time_for_1_centimeter = time_for_1_meter / 100;
const float time_for_360 = 7500;
const float time_per_degree = time_for_360 / 360;

void moveStraight(int sleep_time){
	setMotorSpeed(motorB, 50);
	setMotorSpeed(motorC, 50);
	sleep(sleep_time);
	setMotorSpeed(motorB, 0);
	setMotorSpeed(motorC, 0);
	}

void pointTurn(int degree)
{
	//const float degreePerMillisecond = time_per_degree * degree;
	setMotorSpeed(motorB, -20);
	setMotorSpeed(motorC, 20);
	sleep(degree);
	setMotorSpeed(motorB, 0);
	setMotorSpeed(motorB, 0);
}

void moveBack(int sleep_time)
{
	setMotorSpeed(motorB, -50);
	setMotorSpeed(motorC, -50);
	sleep(sleep_time);
	setMotorSpeed(motorB, 0);
	setMotorSpeed(motorC, 0);
}

task main()
{
	displayTextLine(1, "Start of the program");
	sleep(1000);
	for(int i = 0; i < 3; i++)
	{
		displayTextLine(2, "iteration: %d", i+1);
		moveStraight(time_for_1_centimeter * 10);
		pointTurn(time_per_degree * 60);
		moveStraight(time_for_1_centimeter * 20);
		pointTurn(time_per_degree * 60);
		moveStraight(time_for_1_centimeter * 20);
		pointTurn(time_per_degree * 60);
		moveStraight(time_for_1_centimeter * 20);
		pointTurn(time_per_degree * 60);
		moveStraight(time_for_1_centimeter * 20);
		pointTurn(time_per_degree * 60);
		moveStraight(time_for_1_centimeter * 20);
		pointTurn(time_per_degree * 60);
		moveStraight(time_for_1_centimeter * 10);
		if (i == 2){moveBack(time_for_1_centimeter * 10);}
	}
	eraseDisplay();
	displayTextLine(1, "End of program");
	//moveStraight(time_for_1_centimeter * 10);
	//pointTurn(time_per_degree * 60);
	//moveStraight(time_for_1_centimeter * 20);
	//pointTurn(time_per_degree * 60);
	//moveStraight(time_for_1_centimeter * 20);
	//pointTurn(time_per_degree * 60);
	//moveStraight(time_for_1_centimeter * 20);
	//pointTurn(time_per_degree * 60);
	//moveStraight(time_for_1_centimeter * 20);
	//pointTurn(time_per_degree * 60);
	//moveStraight(time_for_1_centimeter * 20);
	//pointTurn(time_per_degree * 60);
	//moveStraight(time_for_1_centimeter * 20);
}
